### ISSUE TITLE
Wabbajack is selling on "Downloading ISTPS_FullRes 1.0.7z"

### ISSUE THREAD

**Issue by rshackleton** [jdsmith2816/eldersouls#61]
**Describe the bug**
Wabbajack is stalling on "Downloading ISTPS_FullRes 1.0.7z".

First run caused a download failure, this was while the PC was unattended. Second time, currently running, Wabbajack is stalled on that message with no download progress bar on the right.

**To Reproduce**

1. Open wabbajack
2. Download latest modlist
3. Run the modlist install

**Expected behavior**
A full successful install

**Screenshots**

![image](https://user-images.githubusercontent.com/13448395/81652642-f8fc2480-942b-11ea-9221-3053ae5a9b4b.png)

**Modlist version**
v1.1.1

**Did you add any additional mods?**
Nope

**Comment by rshackleton** [comment]
After a few minutes, it displayed this error.

![image](https://user-images.githubusercontent.com/13448395/81654676-a28fe580-942d-11ea-923f-4c2c957d64a1.png)

![image](https://user-images.githubusercontent.com/13448395/81654580-9146d900-942d-11ea-9543-da85cbdacbaf.png)

**Comment by seraphimsake** [comment]
I am not experiencing this issue myself.

**Comment by jdsmith2816** [comment]
If you have trouble downloading Insanity's Texture Pack otherwise seen as ISTPS_FullRes 1.0.7z from TESAlliance please go to http://tesalliance.org/forums/index.php?/files/file/1098-insanitys-texture-pack-skyrim/ and download the file manually.  When it completes place it into your downloads folder and restart wabbajack.

Some people report that it downloads much better utilizing a download manager rather than chrome.

**Comment by rshackleton** [comment]
Cool that worked, couldn't figure out which mod the archive was from so thanks for confirming it.

Hopefully the rest of the install works. :)

**Comment by rshackleton** [comment]
Install worked after a couple of issues on my side, will give it a try tonight. 👍
