### ISSUE TITLE
Random CTD's after loading screenn when entering/exiting/fast travelling

### ISSUE THREAD

**Issue by realVato** [jdsmith2816/eldersouls#79]
I believe it is because of auto saving mechanics?
No additional mods used.
Downloaded and installed through Wabbajack using Nexus Premium.

**Comment by jdsmith2816** [comment]
I don't understand.  There should be no autosaving?

**Comment by ThrasherGX** [comment]
I have also had the occasional ctd when leaving caves/dungeons.

**Comment by realVato** [comment]
Mine are not occassional (although once I was able to play for 3 hrs straight until I exited myself). It's almost predictable, it's very likely to happen in 20-30 minutes of playtime, ctd, jump back in, progress a bit and same pattern.

**Comment by jdsmith2816** [comment]
Wow that has to be really frustrating.

**Comment by ThrasherGX** [comment]
To be honest I am starting to have a similar issue.  It has reached a point that after a certain amount of time playing I always make sure to save before area transitions because crashes have become so common.  

I have no real idea what causes them, and the logs only contain reference values.  I am planning on beginning a new character to see if these crashes are related to my save, or if they are frequent across all characters.

**Comment by jdsmith2816** [comment]
Fixed in 1.3.1
